In [1]:
import numpy as np
import random

#### 1. Count the number of times number appear in Array

In [2]:
array = np.array([1, 2, 1, 3, 4, 1, 4])
num_to_search = 1

num_times = (array == 1).sum()
print('{} is present {} times'.format(num_to_search, num_times))

1 is present 3 times


#### 2. Given 9 integers. Convert in 3x3 numpy array

In [15]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

array = np.array(numbers).reshape((3, 3))
print('Array after reshaping is', array, sep='\n')

Array after reshaping is
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 3. Find memory size of array

In [5]:
array = np.array([1, 2, 3, 4])
print('Size of array is:', len(array) * array.itemsize)

Size of array is: 16


#### Create a 2d array of size 10 by 10 with 1 on the border and 0 inside

In [14]:
array = np.zeros((10, 10))

#Filling 1 on the border

array[0, :] = 1 #Make each element of first row 1
array[:, 0] = 1 #Make each element of first column 1
array[-1, :] = 1 #Make each element of Last row 1
array[:, -1] = 1 #Make each element of last column 1

print('Desired array is', array, sep = '\n')

Desired array is
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 5. Create a matrix 8x8 fill it with checkerboard pattern

In [21]:
mat = np.zeros((8, 8))

#Convert into checkerboard pattern

for i in range(len(mat)):
    if i % 2 == 0:
        mat[i, ::2] = 1
    else:
        mat[i, 1::2] = 1

print('Matrix in checkerboard pattern is', mat, sep='\n')

Matrix in checkerboard pattern is
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 6. Normalize a 5x5 random matrix

In [25]:
a = np.random.rand(5, 5) #Create matrix of size 5x5

print('Matrix before normalization\n', a)

print()
#Normalize the matrix
a = (a - np.mean(a)) / np.std(a)

print('Matrix after normalization\n', a)

Matrix before normalization
 [[0.97521694 0.11966214 0.57488522 0.56955606 0.1484181 ]
 [0.65701219 0.83578468 0.26220137 0.95249786 0.03535124]
 [0.84921977 0.84664607 0.70223456 0.84881402 0.81945126]
 [0.09622357 0.71634478 0.27227565 0.44524543 0.46915403]
 [0.35680985 0.08814824 0.1027875  0.18796695 0.85602425]]

Matrix after normalization
 [[ 1.47814872 -1.24912784  0.20199984  0.18501192 -1.15746162]
 [ 0.46379832  1.03367652 -0.79475143  1.40572646 -1.51788808]
 [ 1.07650394  1.06829969  0.60795498  1.07521053  0.98161   ]
 [-1.32384364  0.65293451 -0.76263736 -0.21125663 -0.1350425 ]
 [-0.49316528 -1.34958559 -1.3029196  -1.03139063  1.09819479]]


#### 7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place

In [36]:
array = np.arange(0, 11)

# Negate elements between 3 and 8
array[np.logical_and(array >= 3, array <= 8)] = array[np.logical_and(array >= 3, array <= 8)] * (-1)
print(array)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 8. How to get Date of yesterday, today and tommorow

In [114]:
today     = np.datetime64('today', 'D')
print("Today's Date ", today)

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ", yesterday)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ", tomorrow)

Today's Date  2020-02-14
Yestraday's Date:  2020-02-13
Tomorrow's Date:  2020-02-15


#### 9. 

#### 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?

In [43]:
array1 = np.array(['cat', 'dog', 'rat'])

array2 = np.random.choice(array1, size=100)

print('Generated 100 elements are', array2, sep='\n')

Generated 100 elements are
['rat' 'rat' 'dog' 'cat' 'dog' 'dog' 'cat' 'cat' 'rat' 'rat' 'cat' 'dog'
 'cat' 'rat' 'rat' 'dog' 'cat' 'dog' 'cat' 'cat' 'cat' 'rat' 'rat' 'cat'
 'dog' 'rat' 'dog' 'dog' 'cat' 'rat' 'rat' 'cat' 'cat' 'rat' 'dog' 'cat'
 'cat' 'rat' 'rat' 'rat' 'cat' 'dog' 'rat' 'rat' 'cat' 'cat' 'rat' 'dog'
 'rat' 'rat' 'dog' 'rat' 'dog' 'rat' 'dog' 'rat' 'cat' 'rat' 'rat' 'rat'
 'cat' 'cat' 'dog' 'rat' 'cat' 'cat' 'dog' 'dog' 'rat' 'dog' 'cat' 'dog'
 'rat' 'cat' 'dog' 'dog' 'cat' 'dog' 'dog' 'rat' 'dog' 'dog' 'rat' 'dog'
 'cat' 'cat' 'dog' 'dog' 'cat' 'cat' 'dog' 'dog' 'dog' 'rat' 'rat' 'cat'
 'dog' 'dog' 'rat' 'cat']


#### 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [54]:
array = np.random.uniform(low=0, high=1, size=10)
print(array)

[0.79116506 0.39659001 0.77934063 0.75246681 0.39524164 0.97560043
 0.54163603 0.83193865 0.32820827 0.19716217]


#### 12. Given a two dimensional array, how to extract unique rows?

In [58]:
mat = np.array([[0, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 0]])

print('Unique rows are', np.unique(mat, axis=0), sep='\n')

Unique rows are
[[0 0 0]
 [0 0 1]]


#### 13.  Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

#### 14. How to find the closest value (to a given scalar) in a vector?

In [59]:
array = np.array([1, 2, 3, 4, 5])

k = 4.01 
closest_value = array[np.abs(array - k).argmin()]

print('Closest value to {} is {}'.format(k, closest_value))

Closest value to 4.01 is 4


#### 15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance

In [64]:
vect = np.random.randn(10, 2)

x,y = np.atleast_2d(vect[:,0], vect[:,1])
dist = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print('Distance between all pais are', dist, sep='\n')

Distance between all pais are
[[0.         1.19275053 2.28822814 2.98153094 1.6697123  3.58296365
  1.40643821 2.70006623 4.75295998 2.07967138]
 [1.19275053 0.         1.17280959 1.85450287 0.78271215 3.32255052
  0.48652398 2.44376993 3.71246786 1.24739203]
 [2.28822814 1.17280959 0.         0.69348093 0.72034748 2.8763772
  0.89483576 2.15056248 2.54406517 0.70546932]
 [2.98153094 1.85450287 0.69348093 0.         1.37383605 2.97572647
  1.58334758 2.41042076 1.90362168 1.17583677]
 [1.6697123  0.78271215 0.72034748 1.37383605 0.         2.60730679
  0.30795191 1.76403919 3.0832542  0.46780435]
 [3.58296365 3.32255052 2.8763772  2.97572647 2.60730679 0.
  2.85109651 0.89825942 3.20130505 2.2436312 ]
 [1.40643821 0.48652398 0.89483576 1.58334758 0.30795191 2.85109651
  0.         1.98350091 3.35783026 0.7752896 ]
 [2.70006623 2.44376993 2.15056248 2.41042076 1.76403919 0.89825942
  1.98350091 0.         3.16445674 1.46332875]
 [4.75295998 3.71246786 2.54406517 1.90362168 3.0832542  3.

#### 16. Sort an array by nth column

In [69]:
array = np.array([[0, 2, 4], [1, 0, 2], [3, 0, 5]])

print('array before sorting', array, sep='\n')

n = 1 #index of column by which array need to sort
array = array[array[:, n].argsort()]

print('Sorted array ', array, sep='\n')

array before sorting
[[0 2 4]
 [1 0 2]
 [3 0 5]]
Sorted array 
[[1 0 2]
 [3 0 5]
 [0 2 4]]


#### 17. How to tell if a given 2D array has null columns?

In [113]:
array = np.array([[0, 1, 2], [2, 3, 4], [4, 5, 6]])
print('array is', array, sep='\n')

#Check if it has null column
print(not(array.any(axis=0)).any())

array is
[[0 1 2]
 [2 3 4]
 [4 5 6]]
False


#### 18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [82]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Array is', array, sep='\n')

print('Sum of last two columns are', np.sum(array[:, -2:]))

Array is
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of last two columns are 33


#### 19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [80]:
array = np.random.rand(5, 5)
print('Original array', array, sep='\n')
#Increment values

for i in range(5):
    array[:, i] += (i+1)
    
print('Modified array', array, sep='\n')

Original array
[[0.07632668 0.09588683 0.80067939 0.92627709 0.02535678]
 [0.48484458 0.11819759 0.74460845 0.17907838 0.32692245]
 [0.59294266 0.49627088 0.66192237 0.05728352 0.18580832]
 [0.93323737 0.36892675 0.71511241 0.14900139 0.76879881]
 [0.11725968 0.95725648 0.87211013 0.16764156 0.64263774]]
Modified array
[[1.07632668 2.09588683 3.80067939 4.92627709 5.02535678]
 [1.48484458 2.11819759 3.74460845 4.17907838 5.32692245]
 [1.59294266 2.49627088 3.66192237 4.05728352 5.18580832]
 [1.93323737 2.36892675 3.71511241 4.14900139 5.76879881]
 [1.11725968 2.95725648 3.87211013 4.16764156 5.64263774]]


#### 20. Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [76]:
array = np.random.choice([True, False], size=100)
print('Array is', array, sep='\n')
print()
print('Number of True are', np.sum(array))

Array is
[ True  True  True False  True  True False  True  True False False  True
  True  True  True False  True False  True  True  True  True False  True
  True False  True False False  True  True False  True  True  True  True
 False False False  True  True False  True False False False False False
 False False  True False False  True False False  True  True False False
  True False False  True False  True False  True  True  True  True False
 False False False  True  True  True  True False False  True  True False
  True  True False False False False  True False False  True  True  True
 False False False False]

Number of True are 51


#### 21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [106]:
vec = np.array([1, 2, 3, 4, 5])

#Number of zeros 
num_zero = 12 #as 3 zeros between each element

#Create array with elements num_zero + len(vec)
new_arr = np.zeros(17)
new_arr[::4] = vec

print('New array is', new_arr, sep='\n')

New array is
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 22. How to swap two rows of an array? 

In [73]:
array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print('Original array is', array, sep='\n')

#Swap row 1 and 2
array[[0, 1]] = array[[1, 0]]
print('Modified array is', array, sep='\n')

Original array is
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Modified array is
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 24. How to get n largest value of an array?

In [90]:
array = np.array([0, 1, 5, 2, 4, 6, 7, 8, 9])
n = 4
array.sort()
print('{} largest values are {}'.format(n, array[-n:]))
print('{}th largest value is {}'.format(n, array[-n]))

4 largest values are [6 7 8 9]
4th largest value is 6


#### 25. Given two random arrays of shape 5X5, identify the common elements between them.

In [96]:
array1 = np.random.randint(1, 5, size=25).reshape((5, 5))
array2 = np.random.randint(1, 5, size=25).reshape((5, 5))

print('array1', array1, sep='\n')
print('array2', array2, sep='\n')
print('Common elements between arrays are', np.intersect1d(array1, array2))

array1
[[3 4 1 4 1]
 [4 3 2 1 4]
 [1 1 1 3 4]
 [3 2 3 1 2]
 [2 2 1 1 2]]
array2
[[4 1 1 3 2]
 [2 2 3 3 2]
 [4 1 2 2 4]
 [1 3 3 3 4]
 [1 1 3 2 1]]
Common elements between arrays are [1 2 3 4]


#### 26. How to get index of top two highest value in a 1d array?

In [101]:
array = np.array([2,22,11,-11,33,7,13,872,-23])
print('Array is ', array)
print('Index of two highest values are', array.argsort()[-2:][::-1])

Array is  [  2  22  11 -11  33   7  13 872 -23]
Index of two highest values are [7 4]
